version: '2'

services:

  wordpress:
    image: wordpress
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    depends_on:
      - mysql
    ports:
      - 9000:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb
    ports: 
      - 9001:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data: 